# Generated by Django 5.2.1 on 2025-07-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='asistentes',
        ),
        migrations.DeleteModel(
            name='AsistenciaEvento',
        ),
    ]
