# Generated by Django 5.2.1 on 2025-07-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('auditoria', 'Auditoría'), ('contrato', 'Contrato'), ('estatutario', 'Estatuto')], max_length=20)),
                ('documento', models.FileField(upload_to='documentos/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
