# Generated by Django 5.2.1 on 2025-07-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentolegal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/imagenes/'),
        ),
    ]
