# Generated by Django 5.2.1 on 2025-07-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documentolegal_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentolegal',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
