# Generated by Django 5.2.1 on 2025-07-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('finanzas', 'Finanzas'), ('eventos', 'Eventos'), ('otros', 'Otros')], default='empresa', max_length=20),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/imagenes/'),
        ),
    ]
