# Generated by Django 5.2.1 on 2025-07-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_categoria_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('business', 'Negocios'), ('economy', 'Economía'), ('politics', 'Política'), ('life', 'Vida'), ('world', 'Mundo'), ('other', 'Otro')], default='other', max_length=20),
        ),
    ]
