# Generated by Django 5.2.1 on 2025-07-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_noticia_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='enlace_externo',
            field=models.URLField(blank=True, help_text='Enlace externo relacionado (fuente, leer más, etc.)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enlace a video externo (YouTube, Vimeo, etc.)', max_length=300, null=True),
        ),
    ]
