# Generated by Django 5.2.1 on 2025-07-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_noticia_enlace_externo_noticia_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='destacada_en_dashboard',
            field=models.BooleanField(default=False, verbose_name='Destacar en Dashboard'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='destacada_hasta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Destacar hasta'),
        ),
    ]
