# Generated by Django 5.2.1 on 2025-07-22 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_groups_alter_usuario_user_permissions'),
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='acciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portafolio', to='accounts.usuario'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='valor_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
