# Generated by Django 5.2.1 on 2025-07-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_alter_portafolio_acciones_alter_portafolio_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolio',
            name='usuario',
        ),
        migrations.AddField(
            model_name='portafolio',
            name='dni',
            field=models.CharField(default='00000000', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='portafolio',
            name='nombre',
            field=models.CharField(default='Accionista', max_length=255),
        ),
    ]
