# Generated by Django 5.2.1 on 2025-07-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_fondo', models.ImageField(blank=True, null=True, upload_to='dashboard/')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Dashboard',
                'verbose_name_plural': 'Configuración Dashboard',
            },
        ),
    ]
