# Generated by Django 5.2.1 on 2025-07-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_configuraciondashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, verbose_name='Mostrar popup')),
                ('titulo', models.CharField(blank=True, max_length=255, verbose_name='Título')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='popups/')),
                ('enlace_boton', models.URLField(blank=True, verbose_name='Enlace del botón')),
                ('texto_boton', models.CharField(blank=True, default='Ver más', max_length=100, verbose_name='Texto del botón')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Mostrar desde')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Mostrar hasta')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Popup Dashboard',
                'verbose_name_plural': 'Popups Dashboard',
            },
        ),
    ]
