# Generated by Django 5.2.1 on 2025-07-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_popupdashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopupDashboard',
        ),
    ]
