# Generated by Django 5.2.1 on 2025-07-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informefinanciero',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
