# Generated by Django 5.2.1 on 2025-07-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_informefinanciero_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informefinanciero',
            name='tipo',
        ),
        migrations.AddField(
            model_name='informefinanciero',
            name='area',
            field=models.CharField(blank=True, choices=[('contabilidad', 'Contabilidad'), ('operaciones', 'Operaciones'), ('comercial', 'Comercial'), ('rrhh', 'Recursos Humanos'), ('legal', 'Legal'), ('finanzas', 'Finanzas'), ('otros', 'Otros')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='informefinanciero',
            name='periodicidad',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='anual', max_length=15),
        ),
        migrations.AddField(
            model_name='informefinanciero',
            name='tipo_informe',
            field=models.CharField(choices=[('financiero', 'Financiero'), ('area', 'Área')], default='financiero', max_length=20),
        ),
    ]
