# Generated by Django 5.2.1 on 2025-07-22 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_groups_alter_usuario_user_permissions'),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtransaccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='accounts.usuario'),
        ),
    ]
