# Generated by Django 5.2.1 on 2025-07-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_mensajesoporte_asunto_mensajesoporte_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=254)),
                ('telefono', models.CharField(default='', max_length=50)),
                ('horario', models.CharField(default='', max_length=100)),
                ('mapa_url', models.URLField(default='')),
                ('facebook', models.URLField(blank=True, default='')),
                ('twitter', models.URLField(blank=True, default='')),
                ('instagram', models.URLField(blank=True, default='')),
                ('linkedin', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Configuración de Contacto',
                'verbose_name_plural': 'Configuración de Contacto',
            },
        ),
    ]
