# Generated by Django 5.2.1 on 2025-07-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0003_contactoconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoconfig',
            name='whatsapp',
            field=models.URLField(blank=True, default=''),
        ),
    ]
