# Generated by Django 5.2.1 on 2025-07-22 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_groups_alter_usuario_user_permissions'),
        ('soporte', '0004_contactoconfig_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajesoporte',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_soporte', to='accounts.usuario'),
        ),
    ]
