# Generated by Django 5.2.1 on 2025-07-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0005_alter_mensajesoporte_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoconfig',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
